spring:
  application:
    name: resonance-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:resonance_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL:false}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

audiodb:
  base-url: https://www.theaudiodb.com/api/v2/json/${AUDIODB_API_KEY}

spotify:
  base-url: https://api.spotify.com/v1
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
