spring:
  application:
    name: resonance-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:resonance_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL:false}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/youtube.readonly
        #          spotify:
        #            client-id: ${SPOTIFY_CLIENT_ID}
        #            client-secret: ${SPOTIFY_CLIENT_SECRET}
        #            authorization-grant-type: authorization_code
        #            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        #            scope:
        #              - user-read-email
        #              - user-read-private
        #        provider:
        #          spotify:
        #            authorization-uri: https://accounts.spotify.com/authorize
        #            token-uri: https://accounts.spotify.com/api/token
        #            user-info-uri: https://api.spotify.com/v1/me
        #            user-name-attribute: id
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000 # 24 hours
      cookie-name: AUTH_TOKEN
  mvc:
    apiversion:
      use:
        header: false
      default: v1

audiodb:
  base-url: https://www.theaudiodb.com/api/v2/json/${AUDIODB_API_KEY}

reccobeats:
  url: https://api.reccobeats.com/v1